"""波形集計・音声ミックス・Craig音声位置合わせで使う NumPy API の最小型定義。"""

from collections.abc import Iterator, Sequence
from typing import overload

from . import fft as fft
from . import testing as testing

class ndarray:
    size: int
    shape: tuple[int, ...]
    ndim: int

    def astype(self, dtype: object, *, copy: bool = ...) -> ndarray: ...
    def reshape(self, *shape: int) -> ndarray: ...
    def mean(self) -> float: ...
    def std(self) -> float: ...
    def tobytes(self) -> bytes: ...
    def copy(self) -> ndarray: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> float: ...
    @overload
    def __getitem__(self, index: slice[int | None, int | None, int | None]) -> ndarray: ...
    @overload
    def __getitem__(self, index: tuple[object, ...] | ndarray) -> ndarray: ...
    def __setitem__(self, index: object, value: object) -> None: ...
    def __add__(self, other: float | ndarray) -> ndarray: ...
    def __iadd__(self, other: float | ndarray) -> ndarray: ...
    def __sub__(self, other: float | ndarray) -> ndarray: ...
    def __rsub__(self, other: float | ndarray) -> ndarray: ...
    def __mul__(self, other: float | ndarray) -> ndarray: ...
    def __rmul__(self, other: float | ndarray) -> ndarray: ...
    def __imul__(self, other: float | ndarray) -> ndarray: ...
    def __truediv__(self, other: float | ndarray) -> ndarray: ...
    def __invert__(self) -> ndarray: ...

class _FloatVector(ndarray):
    @overload
    def __getitem__(self, index: int) -> float: ...
    @overload
    def __getitem__(self, index: slice[int | None, int | None, int | None]) -> _FloatVector: ...
    @overload
    def __getitem__(self, index: tuple[object, ...] | ndarray) -> ndarray: ...
    def __iter__(self) -> Iterator[float]: ...

float32: object
float64: object
uint8: object

def abs(value: ndarray) -> ndarray: ...
def array_split(value: ndarray, sections: int) -> list[ndarray]: ...
@overload
def asarray(value: list[float], dtype: None = ...) -> _FloatVector: ...
@overload
def asarray(value: ndarray | Sequence[float], dtype: object) -> ndarray: ...
def array(value: object, dtype: object = ...) -> ndarray: ...
def frombuffer(buffer: bytes, dtype: object) -> ndarray: ...
def full(shape: int | tuple[int, ...], fill_value: float, dtype: object = ...) -> ndarray: ...
def zeros(shape: int | tuple[int, ...], dtype: object = ...) -> ndarray: ...
def ones(shape: int | tuple[int, ...], dtype: object = ...) -> ndarray: ...
def empty(shape: int | tuple[int, ...], dtype: object = ...) -> ndarray: ...
def concatenate(values: Sequence[ndarray]) -> ndarray: ...
def arange(stop: int, dtype: object = ...) -> ndarray: ...
def repeat(value: ndarray, repeats: int, *, axis: int) -> ndarray: ...
def ascontiguousarray(value: ndarray) -> ndarray: ...
def isfinite(value: ndarray) -> ndarray: ...
def rint(value: ndarray) -> ndarray: ...
def interp(x: ndarray, xp: ndarray, fp: ndarray) -> ndarray: ...
def minimum(left: ndarray, right: float | ndarray) -> ndarray: ...
def sqrt(value: float) -> float: ...
def log10(value: float) -> float: ...
def median(value: Sequence[float]) -> float: ...
def argmax(value: ndarray) -> int: ...
def max(value: ndarray, *, initial: float = ...) -> float: ...
@overload
def mean(value: ndarray, *, axis: None = ..., keepdims: bool = ..., dtype: object = ...) -> float: ...
@overload
def mean(value: ndarray, *, axis: int, keepdims: bool = ..., dtype: object = ...) -> ndarray: ...
def percentile(value: ndarray, q: float) -> float: ...
@overload
def clip(value: float, a_min: float, a_max: float) -> float: ...
@overload
def clip(value: ndarray, a_min: float, a_max: float) -> ndarray: ...
