"""字幕プロジェクトの波形集計で利用する NumPy API の最小型定義。"""

from collections.abc import Iterator

class ndarray:
    size: int

    def astype(self, dtype: object, *, copy: bool = ...) -> ndarray: ...

class _FloatVector(ndarray):
    def __iter__(self) -> Iterator[float]: ...

float32: object

def abs(value: ndarray) -> ndarray: ...
def array_split(value: ndarray, sections: int) -> list[ndarray]: ...
def asarray(value: list[float]) -> _FloatVector: ...
def percentile(value: ndarray, q: float) -> float: ...
def clip(value: float, a_min: float, a_max: float) -> float: ...
