"""旧環境移行 API の互換入口。機能別の実装を再公開する。"""

from __future__ import annotations

import os as os

from .legacy_migration_types import (
    MigrationError as MigrationError,
    RuntimeCapabilities as RuntimeCapabilities,
    INVENTORY_SCHEMA_VERSION as INVENTORY_SCHEMA_VERSION,
    MAX_SIZE_SCAN_ENTRIES as MAX_SIZE_SCAN_ENTRIES,
    STATUS_PRESENT as STATUS_PRESENT,
    STATUS_MISSING as STATUS_MISSING,
    STATUS_UNREADABLE as STATUS_UNREADABLE,
    STATUS_UNSAFE as STATUS_UNSAFE,
    STATUS_NOT_DISCOVERABLE as STATUS_NOT_DISCOVERABLE,
    SCOPE_LEGACY_ROOT as SCOPE_LEGACY_ROOT,
    SCOPE_EXTERNAL as SCOPE_EXTERNAL,
    DISCOVERY_ROOT_RELATIVE as DISCOVERY_ROOT_RELATIVE,
    DISCOVERY_NOT_DISCOVERABLE as DISCOVERY_NOT_DISCOVERABLE,
    CATEGORY_LEGACY_RUNTIME as CATEGORY_LEGACY_RUNTIME,
    CATEGORY_RUNTIME_CONFIG as CATEGORY_RUNTIME_CONFIG,
    CATEGORY_SPEAKER_COLORS as CATEGORY_SPEAKER_COLORS,
    CATEGORY_USER_SETTINGS as CATEGORY_USER_SETTINGS,
    CATEGORY_PROJECT as CATEGORY_PROJECT,
    CATEGORY_MEDIA as CATEGORY_MEDIA,
    CATEGORY_OUTPUT as CATEGORY_OUTPUT,
    CATEGORY_CACHE as CATEGORY_CACHE,
    SETTINGS_MIGRATION_SCHEMA_VERSION as SETTINGS_MIGRATION_SCHEMA_VERSION,
    SETTING_RUNTIME_CONFIG as SETTING_RUNTIME_CONFIG,
    SETTING_SPEAKER_COLORS as SETTING_SPEAKER_COLORS,
    SETTING_DICTIONARY as SETTING_DICTIONARY,
    SETTING_PRESET as SETTING_PRESET,
    SETTING_USER_SETTINGS as SETTING_USER_SETTINGS,
    MIGRATION_ITEM_READY as MIGRATION_ITEM_READY,
    MIGRATION_ITEM_SKIPPED as MIGRATION_ITEM_SKIPPED,
    MIGRATION_ITEM_INVALID as MIGRATION_ITEM_INVALID,
    MIGRATION_OPERATION_COPY as MIGRATION_OPERATION_COPY,
    MIGRATION_OPERATION_SKIP as MIGRATION_OPERATION_SKIP,
    MIGRATION_REASON_DESTINATION_EXISTS as MIGRATION_REASON_DESTINATION_EXISTS,
    MIGRATION_REASON_INVALID as MIGRATION_REASON_INVALID,
    MIGRATION_REASON_NOT_SELECTED as MIGRATION_REASON_NOT_SELECTED,
    MIGRATION_REASON_UNSAFE_SOURCE as MIGRATION_REASON_UNSAFE_SOURCE,
    MIGRATION_REASON_UNSUPPORTED as MIGRATION_REASON_UNSUPPORTED,
    MIGRATION_REASON_EXTERNAL_REFERENCE as MIGRATION_REASON_EXTERNAL_REFERENCE,
    MIGRATION_REASON_CONFIRMATION_REQUIRED as MIGRATION_REASON_CONFIRMATION_REQUIRED,
    MIGRATION_REASON_SOURCE_MISSING as MIGRATION_REASON_SOURCE_MISSING,
    CACHE_CLEANUP_SCHEMA_VERSION as CACHE_CLEANUP_SCHEMA_VERSION,
    CACHE_KIND_PIP_DOWNLOAD as CACHE_KIND_PIP_DOWNLOAD,
    CACHE_KIND_PYTORCH_WHEEL as CACHE_KIND_PYTORCH_WHEEL,
    CACHE_KIND_HUGGINGFACE_WHISPERX_MODEL as CACHE_KIND_HUGGINGFACE_WHISPERX_MODEL,
    CACHE_KIND_PIP as CACHE_KIND_PIP,
    CACHE_KIND_PYTORCH as CACHE_KIND_PYTORCH,
    CACHE_KIND_HUGGINGFACE_MODEL as CACHE_KIND_HUGGINGFACE_MODEL,
    CACHE_KIND_AUDIO_PREVIEW as CACHE_KIND_AUDIO_PREVIEW,
    CACHE_KIND_TRANSCRIPT_METADATA as CACHE_KIND_TRANSCRIPT_METADATA,
    CACHE_KIND_RUNTIME_DEPENDENT as CACHE_KIND_RUNTIME_DEPENDENT,
    CACHE_KIND_LEGACY_VENV as CACHE_KIND_LEGACY_VENV,
    CACHE_KIND_LEGACY_APP_SOURCE as CACHE_KIND_LEGACY_APP_SOURCE,
    CACHE_KIND_PROJECT as CACHE_KIND_PROJECT,
    CACHE_KIND_MEDIA as CACHE_KIND_MEDIA,
    CACHE_KIND_OUTPUT as CACHE_KIND_OUTPUT,
    CACHE_STATE_REUSE as CACHE_STATE_REUSE,
    CACHE_STATE_REBUILD as CACHE_STATE_REBUILD,
    CACHE_STATE_PRESERVE as CACHE_STATE_PRESERVE,
    CACHE_STATE_REMOVABLE_AFTER_SUCCESS as CACHE_STATE_REMOVABLE_AFTER_SUCCESS,
    CLEANUP_STATE_REUSE as CLEANUP_STATE_REUSE,
    CLEANUP_STATE_REBUILD as CLEANUP_STATE_REBUILD,
    CLEANUP_STATE_PRESERVE as CLEANUP_STATE_PRESERVE,
    CLEANUP_STATE_REMOVABLE_AFTER_SUCCESS as CLEANUP_STATE_REMOVABLE_AFTER_SUCCESS,
    CACHE_REASON_NOT_DISCOVERABLE as CACHE_REASON_NOT_DISCOVERABLE,
    CACHE_REASON_REUSE_UNVERIFIED as CACHE_REASON_REUSE_UNVERIFIED,
    CACHE_REASON_PROJECT_PRESERVED as CACHE_REASON_PROJECT_PRESERVED,
    CACHE_REASON_MEDIA_PRESERVED as CACHE_REASON_MEDIA_PRESERVED,
    CACHE_REASON_OUTPUT_PRESERVED as CACHE_REASON_OUTPUT_PRESERVED,
    CACHE_REASON_MIGRATION_INCOMPLETE as CACHE_REASON_MIGRATION_INCOMPLETE,
    CACHE_REASON_LEGACY_ROOT_PRESERVED as CACHE_REASON_LEGACY_ROOT_PRESERVED,
    CACHE_REASON_REFERENCED_DATA as CACHE_REASON_REFERENCED_DATA,
    CACHE_REASON_UNSAFE_PATH as CACHE_REASON_UNSAFE_PATH,
    CACHE_REASON_SOURCE_MISSING as CACHE_REASON_SOURCE_MISSING,
    CACHE_REASON_NOT_SELECTED as CACHE_REASON_NOT_SELECTED,
    CACHE_REASON_NOT_CLEANUP_TARGET as CACHE_REASON_NOT_CLEANUP_TARGET,
    _CANDIDATE_PATHS as _CANDIDATE_PATHS,
    _PROJECT_FILE_SUFFIXES as _PROJECT_FILE_SUFFIXES,
    _EXTERNAL_CACHE_CANDIDATES as _EXTERNAL_CACHE_CANDIDATES,
    LegacyInventoryError as LegacyInventoryError,
    InventoryEntry as InventoryEntry,
    LegacyInventory as LegacyInventory,
    InventoryAction as InventoryAction,
    LegacyMigrationPlan as LegacyMigrationPlan,
    SettingsMigrationOptions as SettingsMigrationOptions,
    SettingsMigrationItem as SettingsMigrationItem,
    LegacySettingsMigrationPlan as LegacySettingsMigrationPlan,
    SettingsMigrationSkip as SettingsMigrationSkip,
    LegacySettingsMigrationResult as LegacySettingsMigrationResult,
    CacheCleanupOptions as CacheCleanupOptions,
    CacheCleanupEntry as CacheCleanupEntry,
    CacheCleanupPlan as CacheCleanupPlan,
    CacheCleanupSkip as CacheCleanupSkip,
    CacheCleanupResult as CacheCleanupResult,
    ChannelPreset as ChannelPreset,
    ChannelPresetError as ChannelPresetError,
    PRESET_SCHEMA_VERSION as PRESET_SCHEMA_VERSION,
    TranscriptionDictionaryError as TranscriptionDictionaryError,
    load_transcription_dictionary as load_transcription_dictionary,
)

from .legacy_migration_inventory import (
    _PathObservation as _PathObservation,
    _lexical_absolute as _lexical_absolute,
    _safe_lstat as _safe_lstat,
    _is_link_like as _is_link_like,
    _size_without_following_links as _size_without_following_links,
    _observe_path as _observe_path,
    _relative_path as _relative_path,
    _entry_for as _entry_for,
    _external_cache_entries as _external_cache_entries,
    _project_file_candidates as _project_file_candidates,
    _root_observation as _root_observation,
    build_legacy_inventory as build_legacy_inventory,
    inventory_legacy_root as inventory_legacy_root,
    build_migration_plan as build_migration_plan,
    build_legacy_migration_plan as build_legacy_migration_plan,
    _SETTING_CATEGORIES as _SETTING_CATEGORIES,
    _json_bytes as _json_bytes,
    _path_is_within as _path_is_within,
    _ensure_safe_destination as _ensure_safe_destination,
)

from .legacy_settings_migration import (
    _setting_kind as _setting_kind,
    _setting_selected as _setting_selected,
    _json_key_paths as _json_key_paths,
    _setting_files as _setting_files,
    _validate_preset_payload as _validate_preset_payload,
    _SECRET_SETTING_KEY_PARTS as _SECRET_SETTING_KEY_PARTS,
    _PATH_SETTING_KEY_PARTS as _PATH_SETTING_KEY_PARTS,
    _is_absolute_setting_value as _is_absolute_setting_value,
    _has_parent_reference as _has_parent_reference,
    _assert_safe_user_setting_payload as _assert_safe_user_setting_payload,
    _safe_setting_file as _safe_setting_file,
    _allowed_setting_relative as _allowed_setting_relative,
    _prepare_runtime_payload as _prepare_runtime_payload,
    _prepare_setting_file as _prepare_setting_file,
    _destination_conflict as _destination_conflict,
    build_settings_migration_plan as build_settings_migration_plan,
    _snapshot_targets as _snapshot_targets,
    _write_bytes_atomic as _write_bytes_atomic,
    _restore_targets as _restore_targets,
    apply_settings_migration as apply_settings_migration,
    build_legacy_settings_migration_plan as build_legacy_settings_migration_plan,
    apply_legacy_settings_migration as apply_legacy_settings_migration,
    apply_migration_plan as apply_migration_plan,
)

from .legacy_cache_cleanup import (
    _cleanup_kind as _cleanup_kind,
    _cleanup_reference_data as _cleanup_reference_data,
    _lookup_cache_path as _lookup_cache_path,
    _cleanup_observation as _cleanup_observation,
    _cleanup_entry_state as _cleanup_entry_state,
    build_cache_cleanup_plan as build_cache_cleanup_plan,
    _cleanup_path_nodes as _cleanup_path_nodes,
    _remove_cleanup_nodes as _remove_cleanup_nodes,
    apply_cache_cleanup as apply_cache_cleanup,
    build_legacy_cache_cleanup_plan as build_legacy_cache_cleanup_plan,
    apply_legacy_cache_cleanup as apply_legacy_cache_cleanup,
    apply_cache_cleanup_plan as apply_cache_cleanup_plan,
    build_cleanup_plan as build_cleanup_plan,
    apply_cleanup_plan as apply_cleanup_plan,
)

__all__ = [
    "CACHE_CLEANUP_SCHEMA_VERSION",
    "CACHE_KIND_AUDIO_PREVIEW",
    "CACHE_KIND_HUGGINGFACE_MODEL",
    "CACHE_KIND_HUGGINGFACE_WHISPERX_MODEL",
    "CACHE_KIND_LEGACY_APP_SOURCE",
    "CACHE_KIND_LEGACY_VENV",
    "CACHE_KIND_MEDIA",
    "CACHE_KIND_OUTPUT",
    "CACHE_KIND_PIP_DOWNLOAD",
    "CACHE_KIND_PIP",
    "CACHE_KIND_PROJECT",
    "CACHE_KIND_PYTORCH_WHEEL",
    "CACHE_KIND_PYTORCH",
    "CACHE_KIND_RUNTIME_DEPENDENT",
    "CACHE_KIND_TRANSCRIPT_METADATA",
    "CACHE_REASON_LEGACY_ROOT_PRESERVED",
    "CACHE_REASON_MEDIA_PRESERVED",
    "CACHE_REASON_MIGRATION_INCOMPLETE",
    "CACHE_REASON_NOT_CLEANUP_TARGET",
    "CACHE_REASON_NOT_DISCOVERABLE",
    "CACHE_REASON_NOT_SELECTED",
    "CACHE_REASON_OUTPUT_PRESERVED",
    "CACHE_REASON_PROJECT_PRESERVED",
    "CACHE_REASON_REUSE_UNVERIFIED",
    "CACHE_REASON_SOURCE_MISSING",
    "CACHE_REASON_UNSAFE_PATH",
    "CACHE_REASON_REFERENCED_DATA",
    "CACHE_STATE_PRESERVE",
    "CACHE_STATE_REBUILD",
    "CACHE_STATE_REMOVABLE_AFTER_SUCCESS",
    "CACHE_STATE_REUSE",
    "CLEANUP_STATE_PRESERVE",
    "CLEANUP_STATE_REBUILD",
    "CLEANUP_STATE_REMOVABLE_AFTER_SUCCESS",
    "CLEANUP_STATE_REUSE",
    "CacheCleanupEntry",
    "CacheCleanupOptions",
    "CacheCleanupPlan",
    "CacheCleanupResult",
    "CacheCleanupSkip",
    "CATEGORY_CACHE",
    "CATEGORY_LEGACY_RUNTIME",
    "CATEGORY_MEDIA",
    "CATEGORY_OUTPUT",
    "CATEGORY_PROJECT",
    "CATEGORY_RUNTIME_CONFIG",
    "CATEGORY_SPEAKER_COLORS",
    "CATEGORY_USER_SETTINGS",
    "DISCOVERY_NOT_DISCOVERABLE",
    "DISCOVERY_ROOT_RELATIVE",
    "INVENTORY_SCHEMA_VERSION",
    "InventoryAction",
    "InventoryEntry",
    "LegacyInventory",
    "LegacyInventoryError",
    "LegacyMigrationPlan",
    "LegacySettingsMigrationPlan",
    "LegacySettingsMigrationResult",
    "SettingsMigrationSkip",
    "MigrationError",
    "MIGRATION_ITEM_INVALID",
    "MIGRATION_ITEM_READY",
    "MIGRATION_ITEM_SKIPPED",
    "MIGRATION_OPERATION_COPY",
    "MIGRATION_OPERATION_SKIP",
    "MIGRATION_REASON_CONFIRMATION_REQUIRED",
    "MIGRATION_REASON_DESTINATION_EXISTS",
    "MIGRATION_REASON_EXTERNAL_REFERENCE",
    "MIGRATION_REASON_INVALID",
    "MIGRATION_REASON_NOT_SELECTED",
    "MIGRATION_REASON_UNSAFE_SOURCE",
    "MIGRATION_REASON_UNSUPPORTED",
    "MIGRATION_REASON_SOURCE_MISSING",
    "RuntimeCapabilities",
    "SETTINGS_MIGRATION_SCHEMA_VERSION",
    "SETTING_DICTIONARY",
    "SETTING_PRESET",
    "SETTING_RUNTIME_CONFIG",
    "SETTING_SPEAKER_COLORS",
    "SETTING_USER_SETTINGS",
    "SettingsMigrationItem",
    "SettingsMigrationOptions",
    "SCOPE_EXTERNAL",
    "SCOPE_LEGACY_ROOT",
    "STATUS_NOT_DISCOVERABLE",
    "STATUS_MISSING",
    "STATUS_PRESENT",
    "STATUS_UNREADABLE",
    "STATUS_UNSAFE",
    "build_legacy_inventory",
    "build_legacy_migration_plan",
    "build_legacy_settings_migration_plan",
    "build_migration_plan",
    "build_settings_migration_plan",
    "apply_legacy_settings_migration",
    "apply_migration_plan",
    "apply_settings_migration",
    "apply_cache_cleanup",
    "apply_cache_cleanup_plan",
    "apply_cleanup_plan",
    "apply_legacy_cache_cleanup",
    "build_cleanup_plan",
    "build_cache_cleanup_plan",
    "inventory_legacy_root",
    "build_legacy_cache_cleanup_plan",
]
